package com.github.syafiqq.unit.conversion.core.unit.compound;

import com.github.syafiqq.unit.conversion.core.unit.single.AreaUnit;
import com.github.syafiqq.unit.conversion.core.unit.single.WeightUnit;

/*
 * This <unit-conversion> created by : 
 * Name         : syafiq
 * Date / Time  : 21 July 2017, 3:12 PM.
 * Email        : syafiq.rezpector@gmail.com
 * Github       : syafiqq
 */
public enum AreaDensityUnit
{
    KILLOTONNE_PER_SQUARE_MILLIMETER(WeightUnit.KILLOTONNE, AreaUnit.SQUARE_MILLIMETER),
    KILLOTONNE_PER_SQUARE_CENTIMETER(WeightUnit.KILLOTONNE, AreaUnit.SQUARE_CENTIMETER),
    KILLOTONNE_PER_SQUARE_DECIMETER(WeightUnit.KILLOTONNE, AreaUnit.SQUARE_DECIMETER),
    KILLOTONNE_PER_SQUARE_METER(WeightUnit.KILLOTONNE, AreaUnit.SQUARE_METER),
    KILLOTONNE_PER_SQUARE_DECAMETER(WeightUnit.KILLOTONNE, AreaUnit.SQUARE_DECAMETER),
    KILLOTONNE_PER_SQUARE_HECTOMETER(WeightUnit.KILLOTONNE, AreaUnit.SQUARE_HECTOMETER),
    KILLOTONNE_PER_SQUARE_KILOMETERS(WeightUnit.KILLOTONNE, AreaUnit.SQUARE_KILOMETERS),
    KILLOTONNE_PER_ARE(WeightUnit.KILLOTONNE, AreaUnit.ARE),
    KILLOTONNE_PER_DECARE(WeightUnit.KILLOTONNE, AreaUnit.DECARE),
    KILLOTONNE_PER_HECTARE(WeightUnit.KILLOTONNE, AreaUnit.HECTARE),
    TONNE_PER_SQUARE_MILLIMETER(WeightUnit.TONNE, AreaUnit.SQUARE_MILLIMETER),
    TONNE_PER_SQUARE_CENTIMETER(WeightUnit.TONNE, AreaUnit.SQUARE_CENTIMETER),
    TONNE_PER_SQUARE_DECIMETER(WeightUnit.TONNE, AreaUnit.SQUARE_DECIMETER),
    TONNE_PER_SQUARE_METER(WeightUnit.TONNE, AreaUnit.SQUARE_METER),
    TONNE_PER_SQUARE_DECAMETER(WeightUnit.TONNE, AreaUnit.SQUARE_DECAMETER),
    TONNE_PER_SQUARE_HECTOMETER(WeightUnit.TONNE, AreaUnit.SQUARE_HECTOMETER),
    TONNE_PER_SQUARE_KILOMETERS(WeightUnit.TONNE, AreaUnit.SQUARE_KILOMETERS),
    TONNE_PER_ARE(WeightUnit.TONNE, AreaUnit.ARE),
    TONNE_PER_DECARE(WeightUnit.TONNE, AreaUnit.DECARE),
    TONNE_PER_HECTARE(WeightUnit.TONNE, AreaUnit.HECTARE),
    KILOGRAM_PER_SQUARE_MILLIMETER(WeightUnit.KILOGRAM, AreaUnit.SQUARE_MILLIMETER),
    KILOGRAM_PER_SQUARE_CENTIMETER(WeightUnit.KILOGRAM, AreaUnit.SQUARE_CENTIMETER),
    KILOGRAM_PER_SQUARE_DECIMETER(WeightUnit.KILOGRAM, AreaUnit.SQUARE_DECIMETER),
    KILOGRAM_PER_SQUARE_METER(WeightUnit.KILOGRAM, AreaUnit.SQUARE_METER),
    KILOGRAM_PER_SQUARE_DECAMETER(WeightUnit.KILOGRAM, AreaUnit.SQUARE_DECAMETER),
    KILOGRAM_PER_SQUARE_HECTOMETER(WeightUnit.KILOGRAM, AreaUnit.SQUARE_HECTOMETER),
    KILOGRAM_PER_SQUARE_KILOMETERS(WeightUnit.KILOGRAM, AreaUnit.SQUARE_KILOMETERS),
    KILOGRAM_PER_ARE(WeightUnit.KILOGRAM, AreaUnit.ARE),
    KILOGRAM_PER_DECARE(WeightUnit.KILOGRAM, AreaUnit.DECARE),
    KILOGRAM_PER_HECTARE(WeightUnit.KILOGRAM, AreaUnit.HECTARE),
    HECTOGRAM_PER_SQUARE_MILLIMETER(WeightUnit.HECTOGRAM, AreaUnit.SQUARE_MILLIMETER),
    HECTOGRAM_PER_SQUARE_CENTIMETER(WeightUnit.HECTOGRAM, AreaUnit.SQUARE_CENTIMETER),
    HECTOGRAM_PER_SQUARE_DECIMETER(WeightUnit.HECTOGRAM, AreaUnit.SQUARE_DECIMETER),
    HECTOGRAM_PER_SQUARE_METER(WeightUnit.HECTOGRAM, AreaUnit.SQUARE_METER),
    HECTOGRAM_PER_SQUARE_DECAMETER(WeightUnit.HECTOGRAM, AreaUnit.SQUARE_DECAMETER),
    HECTOGRAM_PER_SQUARE_HECTOMETER(WeightUnit.HECTOGRAM, AreaUnit.SQUARE_HECTOMETER),
    HECTOGRAM_PER_SQUARE_KILOMETERS(WeightUnit.HECTOGRAM, AreaUnit.SQUARE_KILOMETERS),
    HECTOGRAM_PER_ARE(WeightUnit.HECTOGRAM, AreaUnit.ARE),
    HECTOGRAM_PER_DECARE(WeightUnit.HECTOGRAM, AreaUnit.DECARE),
    HECTOGRAM_PER_HECTARE(WeightUnit.HECTOGRAM, AreaUnit.HECTARE),
    DECAGRAM_PER_SQUARE_MILLIMETER(WeightUnit.DECAGRAM, AreaUnit.SQUARE_MILLIMETER),
    DECAGRAM_PER_SQUARE_CENTIMETER(WeightUnit.DECAGRAM, AreaUnit.SQUARE_CENTIMETER),
    DECAGRAM_PER_SQUARE_DECIMETER(WeightUnit.DECAGRAM, AreaUnit.SQUARE_DECIMETER),
    DECAGRAM_PER_SQUARE_METER(WeightUnit.DECAGRAM, AreaUnit.SQUARE_METER),
    DECAGRAM_PER_SQUARE_DECAMETER(WeightUnit.DECAGRAM, AreaUnit.SQUARE_DECAMETER),
    DECAGRAM_PER_SQUARE_HECTOMETER(WeightUnit.DECAGRAM, AreaUnit.SQUARE_HECTOMETER),
    DECAGRAM_PER_SQUARE_KILOMETERS(WeightUnit.DECAGRAM, AreaUnit.SQUARE_KILOMETERS),
    DECAGRAM_PER_ARE(WeightUnit.DECAGRAM, AreaUnit.ARE),
    DECAGRAM_PER_DECARE(WeightUnit.DECAGRAM, AreaUnit.DECARE),
    DECAGRAM_PER_HECTARE(WeightUnit.DECAGRAM, AreaUnit.HECTARE),
    GRAM_PER_SQUARE_MILLIMETER(WeightUnit.GRAM, AreaUnit.SQUARE_MILLIMETER),
    GRAM_PER_SQUARE_CENTIMETER(WeightUnit.GRAM, AreaUnit.SQUARE_CENTIMETER),
    GRAM_PER_SQUARE_DECIMETER(WeightUnit.GRAM, AreaUnit.SQUARE_DECIMETER),
    GRAM_PER_SQUARE_METER(WeightUnit.GRAM, AreaUnit.SQUARE_METER),
    GRAM_PER_SQUARE_DECAMETER(WeightUnit.GRAM, AreaUnit.SQUARE_DECAMETER),
    GRAM_PER_SQUARE_HECTOMETER(WeightUnit.GRAM, AreaUnit.SQUARE_HECTOMETER),
    GRAM_PER_SQUARE_KILOMETERS(WeightUnit.GRAM, AreaUnit.SQUARE_KILOMETERS),
    GRAM_PER_ARE(WeightUnit.GRAM, AreaUnit.ARE),
    GRAM_PER_DECARE(WeightUnit.GRAM, AreaUnit.DECARE),
    GRAM_PER_HECTARE(WeightUnit.GRAM, AreaUnit.HECTARE),
    DECIGRAM_PER_SQUARE_MILLIMETER(WeightUnit.DECIGRAM, AreaUnit.SQUARE_MILLIMETER),
    DECIGRAM_PER_SQUARE_CENTIMETER(WeightUnit.DECIGRAM, AreaUnit.SQUARE_CENTIMETER),
    DECIGRAM_PER_SQUARE_DECIMETER(WeightUnit.DECIGRAM, AreaUnit.SQUARE_DECIMETER),
    DECIGRAM_PER_SQUARE_METER(WeightUnit.DECIGRAM, AreaUnit.SQUARE_METER),
    DECIGRAM_PER_SQUARE_DECAMETER(WeightUnit.DECIGRAM, AreaUnit.SQUARE_DECAMETER),
    DECIGRAM_PER_SQUARE_HECTOMETER(WeightUnit.DECIGRAM, AreaUnit.SQUARE_HECTOMETER),
    DECIGRAM_PER_SQUARE_KILOMETERS(WeightUnit.DECIGRAM, AreaUnit.SQUARE_KILOMETERS),
    DECIGRAM_PER_ARE(WeightUnit.DECIGRAM, AreaUnit.ARE),
    DECIGRAM_PER_DECARE(WeightUnit.DECIGRAM, AreaUnit.DECARE),
    DECIGRAM_PER_HECTARE(WeightUnit.DECIGRAM, AreaUnit.HECTARE),
    CENTIGRAM_PER_SQUARE_MILLIMETER(WeightUnit.CENTIGRAM, AreaUnit.SQUARE_MILLIMETER),
    CENTIGRAM_PER_SQUARE_CENTIMETER(WeightUnit.CENTIGRAM, AreaUnit.SQUARE_CENTIMETER),
    CENTIGRAM_PER_SQUARE_DECIMETER(WeightUnit.CENTIGRAM, AreaUnit.SQUARE_DECIMETER),
    CENTIGRAM_PER_SQUARE_METER(WeightUnit.CENTIGRAM, AreaUnit.SQUARE_METER),
    CENTIGRAM_PER_SQUARE_DECAMETER(WeightUnit.CENTIGRAM, AreaUnit.SQUARE_DECAMETER),
    CENTIGRAM_PER_SQUARE_HECTOMETER(WeightUnit.CENTIGRAM, AreaUnit.SQUARE_HECTOMETER),
    CENTIGRAM_PER_SQUARE_KILOMETERS(WeightUnit.CENTIGRAM, AreaUnit.SQUARE_KILOMETERS),
    CENTIGRAM_PER_ARE(WeightUnit.CENTIGRAM, AreaUnit.ARE),
    CENTIGRAM_PER_DECARE(WeightUnit.CENTIGRAM, AreaUnit.DECARE),
    CENTIGRAM_PER_HECTARE(WeightUnit.CENTIGRAM, AreaUnit.HECTARE),
    MILIGRAM_PER_SQUARE_MILLIMETER(WeightUnit.MILIGRAM, AreaUnit.SQUARE_MILLIMETER),
    MILIGRAM_PER_SQUARE_CENTIMETER(WeightUnit.MILIGRAM, AreaUnit.SQUARE_CENTIMETER),
    MILIGRAM_PER_SQUARE_DECIMETER(WeightUnit.MILIGRAM, AreaUnit.SQUARE_DECIMETER),
    MILIGRAM_PER_SQUARE_METER(WeightUnit.MILIGRAM, AreaUnit.SQUARE_METER),
    MILIGRAM_PER_SQUARE_DECAMETER(WeightUnit.MILIGRAM, AreaUnit.SQUARE_DECAMETER),
    MILIGRAM_PER_SQUARE_HECTOMETER(WeightUnit.MILIGRAM, AreaUnit.SQUARE_HECTOMETER),
    MILIGRAM_PER_SQUARE_KILOMETERS(WeightUnit.MILIGRAM, AreaUnit.SQUARE_KILOMETERS),
    MILIGRAM_PER_ARE(WeightUnit.MILIGRAM, AreaUnit.ARE),
    MILIGRAM_PER_DECARE(WeightUnit.MILIGRAM, AreaUnit.DECARE),
    MILIGRAM_PER_HECTARE(WeightUnit.MILIGRAM, AreaUnit.HECTARE),
    MICROGRAM_PER_SQUARE_MILLIMETER(WeightUnit.MICROGRAM, AreaUnit.SQUARE_MILLIMETER),
    MICROGRAM_PER_SQUARE_CENTIMETER(WeightUnit.MICROGRAM, AreaUnit.SQUARE_CENTIMETER),
    MICROGRAM_PER_SQUARE_DECIMETER(WeightUnit.MICROGRAM, AreaUnit.SQUARE_DECIMETER),
    MICROGRAM_PER_SQUARE_METER(WeightUnit.MICROGRAM, AreaUnit.SQUARE_METER),
    MICROGRAM_PER_SQUARE_DECAMETER(WeightUnit.MICROGRAM, AreaUnit.SQUARE_DECAMETER),
    MICROGRAM_PER_SQUARE_HECTOMETER(WeightUnit.MICROGRAM, AreaUnit.SQUARE_HECTOMETER),
    MICROGRAM_PER_SQUARE_KILOMETERS(WeightUnit.MICROGRAM, AreaUnit.SQUARE_KILOMETERS),
    MICROGRAM_PER_ARE(WeightUnit.MICROGRAM, AreaUnit.ARE),
    MICROGRAM_PER_DECARE(WeightUnit.MICROGRAM, AreaUnit.DECARE),
    MICROGRAM_PER_HECTARE(WeightUnit.MICROGRAM, AreaUnit.HECTARE),
    NANOGRAM_PER_SQUARE_MILLIMETER(WeightUnit.NANOGRAM, AreaUnit.SQUARE_MILLIMETER),
    NANOGRAM_PER_SQUARE_CENTIMETER(WeightUnit.NANOGRAM, AreaUnit.SQUARE_CENTIMETER),
    NANOGRAM_PER_SQUARE_DECIMETER(WeightUnit.NANOGRAM, AreaUnit.SQUARE_DECIMETER),
    NANOGRAM_PER_SQUARE_METER(WeightUnit.NANOGRAM, AreaUnit.SQUARE_METER),
    NANOGRAM_PER_SQUARE_DECAMETER(WeightUnit.NANOGRAM, AreaUnit.SQUARE_DECAMETER),
    NANOGRAM_PER_SQUARE_HECTOMETER(WeightUnit.NANOGRAM, AreaUnit.SQUARE_HECTOMETER),
    NANOGRAM_PER_SQUARE_KILOMETERS(WeightUnit.NANOGRAM, AreaUnit.SQUARE_KILOMETERS),
    NANOGRAM_PER_ARE(WeightUnit.NANOGRAM, AreaUnit.ARE),
    NANOGRAM_PER_DECARE(WeightUnit.NANOGRAM, AreaUnit.DECARE),
    NANOGRAM_PER_HECTARE(WeightUnit.NANOGRAM, AreaUnit.HECTARE);

    static final double MAX = Double.MAX_VALUE;
    private final WeightUnit weight;
    private final AreaUnit area;

    AreaDensityUnit(WeightUnit weight, AreaUnit area)
    {
        this.weight = weight;
        this.area = area;
    }

    static double eval(double d, double m, double over)
    {
        if(d > over)
        {
            return Double.MAX_VALUE;
        }
        if(d < -over)
        {
            return Double.MIN_VALUE;
        }
        return d * m;
    }

    public double to(AreaDensityUnit sourceUnit, double sourceArea)
    {
        return this.to(sourceUnit.weight, sourceUnit.area, sourceArea);
    }

    private double to(WeightUnit weight, AreaUnit area, double sourceArea)
    {
        double calculate = (this.weight.base / weight.base) / (this.area.base / area.base);
        return eval(sourceArea, (calculate), MAX / (calculate));
    }
}
